-- 0052: real BJCP-grounded sensory profile + taste + typical ingredients + history
-- for every style, so EVERY recognizable beer gets depth (hoppiness/bitterness/
-- sourness/body/etc., what it tastes like, what is typically in it, where it comes
-- from). Values are style-typical (honest), never per-beer invented. 0-5 scales.
alter table public.beer_style_reference
  add column if not exists hoppiness smallint,
  add column if not exists bitterness smallint,
  add column if not exists sweetness smallint,
  add column if not exists body smallint,
  add column if not exists roast smallint,
  add column if not exists sourness smallint,
  add column if not exists fruitiness smallint,
  add column if not exists flavor_notes text,
  add column if not exists typical_ingredients text,
  add column if not exists style_history text;

update public.beer_style_reference r set
  hoppiness = v.hop, bitterness = v.bit, sweetness = v.swe, body = v.bod,
  roast = v.ro, sourness = v.so, fruitiness = v.fr,
  flavor_notes = v.flav, typical_ingredients = v.ing, style_history = v.hist
from (values
 ('Altbier',3,3,2,3,1,0,1,'Bready malt with a firm, clean bitter finish.','Munich and Vienna malts, Spalt hops, clean ale yeast, cold-conditioned.','Dusseldorf''s traditional top-fermented "old" ale, lagered cold.'),
 ('American Amber Ale',3,3,3,3,1,0,1,'Caramel malt meets citrusy American hops, balanced and easygoing.','Pale and crystal malts, American hops, clean ale yeast.','West Coast craft''s malt-and-hop balanced amber.'),
 ('American Brown Ale',3,3,3,3,2,0,1,'Chocolate and caramel malt with a citrusy American hop kick.','Pale, crystal and chocolate malts, American hops.','Craft-era hoppier take on the English brown ale.'),
 ('California Common',3,3,2,3,1,0,1,'Toasty and lightly fruity with woody Northern Brewer hops.','Pale and crystal malt, Northern Brewer hops, lager yeast fermented warm.','San Francisco "steam beer", lager yeast at cellar temps.'),
 ('English Brown Ale',2,2,3,3,2,0,2,'Malty, nutty and caramel, gentle and sessionable.','Mild and crystal malts, English hops, English ale yeast.','Northern English brown, a maltier cousin of mild.'),
 ('Irish Red Ale',2,2,3,3,2,0,1,'Caramel sweetness with a dry, lightly roasted finish.','Pale and caramel malt, a touch of roasted barley, ale yeast.','Easy-drinking Irish amber with a hint of roast for dryness.'),
 ('Kölsch',2,3,2,2,0,0,2,'Crisp and delicate, soft malt with a subtle wine-like fruit.','Pilsner malt, German noble hops, kölsch yeast, cold-conditioned.','Cologne''s protected hybrid: ale-fermented, lager-conditioned.'),
 ('Belgian Blond Ale',2,2,3,3,0,0,3,'Soft golden Belgian with subtle spice and light fruit.','Pilsner malt, sugar, Belgian yeast, noble hops.','Belgium''s approachable, softly spiced answer to pilsner.'),
 ('Belgian Dark Strong Ale',2,2,4,4,2,0,4,'Rich and dark, dried fruit and caramel with warming strength.','Pilsner and specialty malts, dark candi sugar, Belgian yeast.','The quadrupel zone, Trappist-inspired dark strong ale.'),
 ('Belgian Dubbel',2,2,3,3,2,0,4,'Deep reddish-brown, raisin and caramel with Belgian spice.','Pilsner malt, dark candi sugar, Belgian yeast.','Trappist "double", richer and darker than the single.'),
 ('Belgian Golden Strong Ale',2,3,2,3,0,0,4,'Pale and effervescent, spicy and fruity, dangerously strong.','Pilsner malt, sugar, Belgian yeast, noble hops.','Devilishly strong pale Belgian ale, born to rival Duvel.'),
 ('Belgian Tripel',2,3,2,3,0,0,4,'Strong, spicy and dry golden ale that hides its potency.','Pilsner malt, sugar, Belgian yeast, noble hops.','Trappist "triple", pale and deceptively strong.'),
 ('Saison',3,3,1,2,0,1,3,'Dry and peppery, spicy yeast with high, refreshing carbonation.','Pilsner malt, wheat, saison yeast, noble hops.','Wallonian farmhouse ale brewed for summer field workers.'),
 ('Best Bitter',3,3,2,2,1,0,2,'Malty and fruity with a firm, sessionable bitter finish.','Pale and crystal malt, English hops, English ale yeast.','The classic pub bitter, flavorful yet low in strength.'),
 ('Strong Bitter (ESB)',3,4,3,3,1,0,2,'Richer and hoppier bitter, caramel malt and English hops.','Pale and crystal malt, English hops, English ale yeast.','Extra Special Bitter, Fuller''s ESB the archetype.'),
 ('Doppelbock',2,2,4,4,2,0,2,'Strong and very malty, toast and caramel, "liquid bread".','Munich and Pilsner malt, noble hops, lager yeast.','Munich monks'' "double bock", brewed to sustain Lenten fasts.'),
 ('Dunkles Bock',2,2,3,4,2,0,1,'Dark and strong, bread crust and caramel.','Munich and Vienna malt, noble hops, lager yeast.','Traditional dark bock from Einbeck, later Munich.'),
 ('Helles Bock (Maibock)',3,3,3,3,0,0,1,'Paler and strong, malty with a touch of noble hop.','Pilsner and Munich malt, noble hops, lager yeast.','Spring "May bock", paler and hoppier than dark bock.'),
 ('Porter',2,3,2,3,3,0,1,'Chocolate and toast with a moderate roast.','Pale, crystal and chocolate malts, English hops.','18th-century London''s working-class dark ale.'),
 ('Stout',2,3,2,3,4,0,1,'Coffee and cocoa with a dry, roasty finish.','Pale malt, roasted barley, English hops.','The stronger, roastier "stout porter" that became its own family.'),
 ('American IPA',5,4,2,2,0,0,2,'Citrus, pine and tropical hops over a lean malt base.','Pale malt, American hops (Cascade, Citra and kin), clean ale yeast.','The beer that launched the US craft hop revolution.'),
 ('Double IPA',5,5,2,3,0,0,3,'Intensely hoppy and strong, a showcase for American hops.','Pale malt, heavy American hopping, clean ale yeast.','The West Coast "imperial" IPA, hops turned to eleven.'),
 ('English IPA',3,4,3,3,1,0,2,'Earthy, floral English hops over biscuity malt, well-attenuated.','English pale malt, English hops, English ale yeast.','The original IPA, hopped to survive the voyage to India.'),
 ('Hazy IPA',5,2,2,3,0,0,4,'Soft and juicy, low bitterness, pillowy body, big tropical aroma.','Pale malt, oats and wheat, late and dry American hops, hazy yeast.','New England''s opaque, juice-forward IPA.'),
 ('West Coast IPA',5,5,1,2,0,0,2,'Clear and dry with citrus, pine and resin.','Pale malt, American hops, clean ale yeast.','California''s crisp, aggressively bitter IPA archetype.'),
 ('American Lager',1,1,2,1,0,0,0,'Very pale, crisp and clean with gentle carbonation.','Pilsner malt, corn or rice, light hopping, lager yeast.','The mass-market American adjunct lager.'),
 ('American Light Lager',1,1,1,1,0,0,0,'Nearly flavor-neutral, highly carbonated and very light.','Pilsner malt, corn or rice, minimal hops, lager yeast.','The low-calorie "lite" lager.'),
 ('Czech Premium Pale Lager',4,4,3,3,0,0,1,'Rich and characterful, spicy Saaz over buttery-soft malt.','Czech Pilsner malt, Saaz hops, decoction mash, lager yeast.','Pilsner Urquell''s homeland style, the original pale lager dialed up.'),
 ('Festbier',2,3,3,3,0,0,1,'Smooth, clean and pale, the modern Oktoberfest pour.','Pilsner and Munich malt, noble hops, lager yeast.','The paler lager served at today''s Oktoberfest.'),
 ('German Pils',4,4,2,2,0,0,0,'Pale, crisp and dry with a lasting noble-hop bitterness.','Pilsner malt, German noble hops, soft water, lager yeast.','Northern Germany''s drier, hoppier take on pilsner.'),
 ('Helles',2,2,3,3,0,0,0,'Soft and malty with gentle bitterness.','Pilsner malt, noble hops, lager yeast.','Munich''s malt-forward answer to pilsner.'),
 ('International Pale Lager',2,2,2,2,0,0,0,'Clean, crisp and universal, the everyday golden lager.','Pilsner malt, adjuncts, light hopping, lager yeast.','The globe-spanning premium lager (Heineken, Stella and kin).'),
 ('Märzen',2,3,3,3,1,0,1,'Amber and toasty, malty with a clean dry finish.','Munich and Vienna malt, noble hops, lager yeast.','Brewed in March, lagered for the original Oktoberfest.'),
 ('Munich Dunkel',2,2,3,3,2,0,1,'Bready and chocolatey dark lager that stays smooth.','Munich malt, noble hops, lager yeast.','Munich''s original everyday dark lager.'),
 ('Munich Helles',2,2,3,3,0,0,0,'Clean and malty gold lager with soft bread flavor.','Pilsner malt, noble hops, lager yeast.','Munich''s beloved pale lager, malt over hops.'),
 ('Pilsner',4,4,2,2,0,0,0,'Bright, pale and crisp with expressive noble-hop bitterness.','Pilsner malt, noble hops, soft water, lager yeast.','Born in Plzen in 1842, the first golden lager.'),
 ('Schwarzbier',2,3,2,2,3,0,0,'Dark lager balancing smooth coffee roast with a light body.','Pilsner and roasted malts, noble hops, lager yeast.','Eastern Germany''s "black beer", roast without the heaviness.'),
 ('Vienna Lager',2,3,3,3,1,0,1,'Soft and smooth amber lager with toasty Vienna malt.','Vienna malt, noble hops, lager yeast.','Anton Dreher''s 1841 amber lager, later famous in Mexico.'),
 ('Non-Alcoholic IPA',4,3,2,2,0,0,2,'Hop-forward IPA character at little to no alcohol.','Pale malt, American hops; alcohol removed or arrested.','The NA craft wave''s hoppy flagship.'),
 ('Non-Alcoholic Beer',2,2,2,2,0,0,0,'Full beer flavor at 0.5% ABV or below.','Malt, hops, yeast; alcohol removed or fermentation arrested.','Alcohol-free brewing, now a fast-growing category.'),
 ('American Pale Ale',4,3,2,2,0,0,2,'Hop-forward but balanced, citrus and pine over clean malt.','Pale and crystal malt, American hops, clean ale yeast.','Sierra Nevada Pale Ale''s template, craft''s gateway beer.'),
 ('Blonde Ale',2,2,3,2,0,0,1,'Easy and approachable, lightly malty with a soft hop touch.','Pale malt, light hops, clean ale yeast.','Craft brewers'' friendly crossover ale.'),
 ('American Porter',3,3,2,3,3,0,1,'Robust chocolate and coffee with American hop support.','Pale, crystal and chocolate malt, American hops.','Craft-era bolder, roastier porter.'),
 ('Baltic Porter',2,3,4,4,3,0,2,'Strong and smooth dark porter, rich and clean.','Munich and roasted malts, lager yeast, cold-conditioned.','The Baltic states'' strong porter, brewed with lager yeast.'),
 ('English Porter',2,3,2,3,3,0,1,'Restrained-roast brown-black ale, chocolate and toffee.','Pale, crystal and brown or chocolate malt, English hops.','London''s original porter, moderate and smooth.'),
 ('Foreign Extra Stout',2,4,2,3,4,0,2,'Very dark, strong and roasty, brewed for export.','Pale malt, roasted barley, hops.','The tropicalized export stout (Guinness FES).'),
 ('Imperial Stout',3,4,3,5,5,0,3,'Huge and roasty, coffee, chocolate and dark fruit, warming.','A big pale malt bill, roasted malts, generous hops.','Brewed strong for the Russian Imperial court.'),
 ('Irish Stout',2,3,1,2,4,0,1,'Black, dry and roasty with a coffee-like bitterness.','Pale malt, flaked barley, roasted barley, hops.','Dublin''s dry stout, Guinness the icon.'),
 ('Oatmeal Stout',2,3,3,4,3,0,1,'Silky and full-bodied with a smooth oat softness.','Pale and roasted malt, oats, hops.','Victorian "nourishing" stout with oats for body.'),
 ('Sweet Stout',2,2,4,4,3,0,1,'Dark and sweet, milk sugar softens the roast.','Pale and roasted malt, lactose (milk sugar), hops.','"Milk stout", lactose adds unfermentable sweetness.'),
 ('Berliner Weisse',1,1,1,1,0,4,2,'Very pale, tart and refreshing, low in alcohol.','Pilsner and wheat malt, Lactobacillus, low hops.','Berlin''s "Champagne of the North", often served with syrup.'),
 ('Flanders Red Ale',1,1,2,2,1,4,4,'Sour, fruity and wine-like, aged in oak.','Vienna and Munich malt, mixed culture, oak-aged.','West Flanders'' oak-aged sour red (Rodenbach).'),
 ('Gose',1,1,1,2,0,4,2,'Tart wheat ale with coriander and a whisper of salt.','Pilsner and wheat malt, salt, coriander, Lactobacillus.','Leipzig''s salty-sour wheat, revived by US craft.'),
 ('Gueuze',1,1,1,2,0,5,3,'Complex, sour and funky blend of young and old lambic.','Barley and unmalted wheat, spontaneous fermentation, oak-aged.','Blended lambic from Brussels'' Senne valley.'),
 ('Rauchbier',2,3,3,3,1,0,1,'An amber Marzen with a distinctive beechwood smoke.','Beechwood smoked malt, Munich malt, noble hops, lager yeast.','Bamberg''s smoked lager (Schlenkerla).'),
 ('English Barleywine',3,4,4,5,1,0,4,'Intense and rich, dark fruit, toffee and warming alcohol.','A huge pale malt bill, English hops, ale yeast, long aging.','The strongest, richest English ale, often vintage-aged.'),
 ('Old Ale',2,3,4,4,2,1,4,'Aged, malty and warming, dark fruit and toffee.','Pale and specialty malt, English hops, long conditioning.','"Stock" ale aged for depth, sometimes lightly tart.'),
 ('American Wheat',3,2,2,2,0,0,2,'Refreshing wheat beer, clean yeast, more hop than German styles.','Wheat and pale malt, American hops, clean ale yeast.','US craft''s cleaner take on wheat beer.'),
 ('Weissbier',1,1,3,3,0,0,4,'Pale wheat beer bursting with banana and clove yeast.','Wheat and barley malt, weizen yeast, noble hops.','Bavaria''s classic hefeweizen, driven by its yeast.'),
 ('Weizenbock',2,2,4,4,2,0,4,'Strong malty wheat ale, banana, clove and dark fruit.','Wheat and Munich malt, weizen yeast, noble hops.','The bock-strength version of weissbier.'),
 ('Witbier',2,2,2,2,0,1,3,'Refreshing Belgian wheat with orange peel and coriander.','Unmalted wheat and barley, orange peel, coriander, Belgian yeast.','Belgium''s spiced "white beer" (Hoegaarden revived it).')
) as v(name, hop, bit, swe, bod, ro, so, fr, flav, ing, hist)
where r.style_name = v.name;
