-- 0057_branded_web_domain.sql
-- Use the production Tapt domain for every partner CTA generated by the backend.

update public.featured_partner
set cta_url = replace(cta_url, 'https://tapt-landing-three.vercel.app', 'https://taptbeer.com'),
    updated_at = now()
where cta_url like 'https://tapt-landing-three.vercel.app/%';

create or replace function public.grant_featured(
  p_venue uuid,
  p_tier text default 'featured',
  p_days integer default 30,
  p_title text default null,
  p_blurb text default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
  v_name text;
  v_city text;
  v_region text;
  v_country text;
begin
  if not public.is_admin() then raise exception 'admin only'; end if;
  if p_tier not in ('featured', 'spotlight') then
    raise exception 'tier must be featured or spotlight';
  end if;

  select ve.name,
         ve.external_ids->>'city',
         ve.external_ids->>'region',
         ve.external_ids->>'country'
  into v_name, v_city, v_region, v_country
  from public.venue ve
  where ve.id = p_venue;
  if v_name is null then raise exception 'venue not found'; end if;

  insert into public.featured_partner
    (kind, venue_id, title, blurb, cta_label, cta_url, city, region,
     country, tier, starts_at, ends_at, active, sort_rank)
  values
    ('venue', p_venue, coalesce(p_title, v_name),
     coalesce(p_blurb, 'Featured on Tapt'), 'View menu',
     'https://taptbeer.com/menu?v=' || p_venue::text,
     v_city, v_region, v_country, p_tier, now(),
     now() + make_interval(days => p_days), true,
     case when p_tier = 'spotlight' then 0 else 100 end)
  returning id into v_id;
  return v_id;
end;
$$;

revoke all on function public.grant_featured(uuid, text, integer, text, text)
  from public, anon, authenticated;
grant execute on function public.grant_featured(uuid, text, integer, text, text)
  to authenticated;

notify pgrst, 'reload schema';
