-- 0065_media_pipeline_and_security_cleanup.sql
-- Track real-photo cutout processing, make the write path server-only, and
-- resolve the actionable database advisor findings without fabricating media.

create table if not exists public.beer_media_processing (
  beer_id uuid primary key references public.beer_catalog(id) on delete cascade,
  source_url text not null,
  source_sha256 text,
  status text not null check (status in ('processing', 'completed', 'retry', 'rejected')),
  attempts integer not null default 0 check (attempts between 0 and 20),
  output_width integer,
  output_height integer,
  foreground_fraction numeric(6,5),
  error_code text,
  updated_at timestamptz not null default now()
);

create index if not exists beer_media_processing_status
  on public.beer_media_processing (status, attempts, updated_at);

alter table public.beer_media_processing enable row level security;
revoke all on public.beer_media_processing from anon, authenticated;
grant select, insert, update, delete on public.beer_media_processing to service_role;

-- Product cutouts are generated by the controlled Actions pipeline. A normal
-- signed-in app user must never be able to replace catalog artwork.
drop policy if exists cutouts_write on storage.objects;
drop policy if exists cutouts_update on storage.objects;
drop policy if exists cutouts_delete on storage.objects;

-- Avoid evaluating auth.uid() once per beer-note row.
drop policy if exists beer_note_own on public.beer_note;
create policy beer_note_own on public.beer_note
  for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

-- The Cellar read model pages in this order.
create index if not exists checkin_event_user_time
  on public.checkin_event (user_id, event_ts desc, id desc);

-- The remaining spatial_ref_sys advisor finding belongs to the Supabase-owned
-- PostGIS extension. Project migrations cannot alter that extension-owned table;
-- direct Tapt table access remains revoked by the launch hardening migration.

notify pgrst, 'reload schema';
