-- Audit fix (licensing): the 199 Wikimedia Commons photos we display were stored
-- with label_image_license = 'Wikimedia Commons (P18)'. That is not a license and
-- names no author, and the beer page renders it verbatim as
-- "Label photo: Wikimedia Commons (P18)". Once the in-app image gate was opened
-- to source photos those CC BY-SA images went live with attribution that
-- satisfies no license.
--
-- Real author + license fetched per file from the Commons API (imageinfo
-- extmetadata: Artist, LicenseShortName) and stored as
-- "<Author> · <License> · Wikimedia Commons", which the existing sourcesFooter
-- renders as a compliant credit. All 199 resolved; nothing invented.
-- Licenses present: CC BY-SA 3.0/4.0/2.0/2.5, CC BY 2.0/3.0/4.0/2.5, CC0,
-- public domain.
update public.beer_catalog b set label_image_license = v.attrib
from (values
  ('20110703_Huizingen_%280050%29.jpg','20110703%20Huizingen%20%280050%29.jpg','Donar Reiskoffer · CC BY 3.0 · Wikimedia Commons'),
  ('AR-MEN_%28beer%29.JPG','AR-MEN%20%28beer%29.JPG','(c) 2005 Zubro · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Abbaye_d%27Aulne_Triple_blonde.JPG','Abbaye%20d%27Aulne%20Triple%20blonde.JPG','Queeste · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Abdijbier2_abbayedeforest.jpg','Abdijbier2%20abbayedeforest.jpg','Dirk Van Esbroeck · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Abdijbier5_stmartin.jpg','Abdijbier5%20stmartin.jpg','Dirk Van Esbroeck · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Abtbier_12.jpg','Abtbier%2012.jpg','Kungfuman · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Alfa_Bokbier.jpg','Alfa%20Bokbier.jpg','FakirNL · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Alfa_Edel_Pils.jpg','Alfa%20Edel%20Pils.jpg','FakirNL · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Alfa_Lente_Bok_%28sic%29.jpg','Alfa%20Lente%20Bok%20%28sic%29.jpg','FakirNL · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Alfa_Oud_Bruin.jpg','Alfa%20Oud%20Bruin.jpg','FakirNL · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Alfa_Super_Dortmunder.jpg','Alfa%20Super%20Dortmunder.jpg','FakirNL · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Alfa_Super_Strong_9.2.jpg','Alfa%20Super%20Strong%209.2.jpg','FakirNL · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Alpaide.jpg','Alpaide.jpg','DirkVE · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Alternatief_Ambetanterik.jpg','Alternatief%20Ambetanterik.jpg','Bernt Rostad from Oslo, Norway · CC BY 2.0 · Wikimedia Commons'),
  ('Alvinne_Caper_Fumatis.jpg','Alvinne%20Caper%20Fumatis.jpg','Dirk Van Esbroeck · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Amstel_Bock.JPG','Amstel%20Bock.JPG','Queeste · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Amstel_Pils.jpg','Amstel%20Pils.jpg','FakirNL · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Amstel_Radler.jpg','Amstel%20Radler.jpg','FakirNL · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Anker_pils.JPG','Anker%20pils.JPG','Soti · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Bacchus_frambozenbier.JPG','Bacchus%20frambozenbier.JPG','Soti · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Barbe_d%27Or.JPG','Barbe%20d%27Or.JPG','Soti · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Bavaria_0%2C0%25_Gold.jpg','Bavaria%200%2C0%25%20Gold.jpg','Jasper K · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Bavaria_0.0%25.jpg','Bavaria%200.0%25.jpg','Grasmat · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Bavaria_Premium_Pilsener_%28new_design%29.jpg','Bavaria%20Premium%20Pilsener%20%28new%20design%29.jpg','FakirNL · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Beer_Bernard_1.jpg','Beer%20Bernard%201.jpg','Karelj · Public domain · Wikimedia Commons'),
  ('Beer_Lobkowicz_Ale.jpg','Beer%20Lobkowicz%20Ale.jpg','Pastorius · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Beer_glass_La_Biere_Du_Demon.jpg','Beer%20glass%20La%20Biere%20Du%20Demon.jpg','Flazaza · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Bier_brouwerijverhaeghe.jpg','Bier%20brouwerijverhaeghe.jpg','Dirk Van Esbroeck · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Bier_duchessedebourgogne.jpg','Bier%20duchessedebourgogne.jpg','Dirk Van Esbroeck · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Bier_montdescats.jpg','Bier%20montdescats.jpg','Dirk Van Esbroeck · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Bieres-de-paques.jpg','Bieres-de-paques.jpg','Aloxe · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Birell_svetly.jpg','Birell%20svetly.jpg','JiriMatejicek · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Bitterewaarheid.jpg','Bitterewaarheid.jpg','DirkVE · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Bi%C3%A8re_D%C3%A9lirium_tremens.JPG','Bi%C3%A8re%20D%C3%A9lirium%20tremens.JPG','Bierologue59 · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Bi%C3%A8re_Laurentide.JPG','Bi%C3%A8re%20Laurentide.JPG','Khayman · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Blanche_de_Namur.JPG','Blanche%20de%20Namur.JPG','LeeKeoma · CC0 · Wikimedia Commons'),
  ('Blanches.jpg','Blanches.jpg','Rafael Pauwels · CC BY-SA 2.5 · Wikimedia Commons'),
  ('BlondineIPA.jpg','BlondineIPA.jpg','DirkVE · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Blue_Moon_beer_with_orange.jpg','Blue%20Moon%20beer%20with%20orange.jpg','Secretlondon · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Bokbier.jpg','Bokbier.jpg','Michiel1972 at Dutch Wikipedia · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Bonne_Esperance.JPG','Bonne%20Esperance.JPG','Soti · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Bottle_of_Herold_beer.jpg','Bottle%20of%20Herold%20beer.jpg','CC BY-SA 3.0 · Wikimedia Commons'),
  ('Brand_Dubbelbock_2014.jpg','Brand%20Dubbelbock%202014.jpg','Jasper K · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Brand_IPA.jpg','Brand%20IPA.jpg','Jasper K · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Brand_Imperator_2014.jpg','Brand%20Imperator%202014.jpg','Jasper K · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Brand_Lentebock_2015.jpg','Brand%20Lentebock%202015.jpg','Jasper K · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Brand_Oud_Bruin_2014.jpg','Brand%20Oud%20Bruin%202014.jpg','Jasper K · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Brand_Pilsener_2014.jpg','Brand%20Pilsener%202014.jpg','Jasper K · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Brand_Sylvester.jpg','Brand%20Sylvester.jpg','Jasper K · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Brand_UP_2014.jpg','Brand%20UP%202014.jpg','Jasper K · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Brand_Weizen_2014.jpg','Brand%20Weizen%202014.jpg','Jasper K · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Brewmeister_Armageddon.jpg','Brewmeister%20Armageddon.jpg','Brett Jordan · CC BY 2.0 · Wikimedia Commons'),
  ('Brouwerij_%27t_IJ_I.P.A._%28old_design%29.jpg','Brouwerij%20%27t%20IJ%20I.P.A.%20%28old%20design%29.jpg','Lars van der Heide · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Brouwerij_%27t_IJ_IJwit_%28bottle%29.jpg','Brouwerij%20%27t%20IJ%20IJwit%20%28bottle%29.jpg','FakirNL · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Brouwers_%28AH%29_Pilsener_%28.33_can%29.jpg','Brouwers%20%28AH%29%20Pilsener%20%28.33%20can%29.jpg','FakirNL · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Brugge_Tripel.jpg','Brugge%20Tripel.jpg','Le Fou · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Budvar_UK.JPG','Budvar%20UK.JPG','ML5 at English Wikipedia · Public domain · Wikimedia Commons'),
  ('Cambron_Blonde.jpg','Cambron%20Blonde.jpg','Beireke1 · CC0 · Wikimedia Commons'),
  ('Cardinal_Gasterntal.JPG','Cardinal%20Gasterntal.JPG','Adrian Michael · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Carlsberg_beer.jpg','Carlsberg%20beer.jpg','Hawyih · Public domain · Wikimedia Commons'),
  ('CastleLagerandGlass2016.jpg','CastleLagerandGlass2016.jpg','Britfan97 · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Cerna_hora_diamant.jpg','Cerna%20hora%20diamant.jpg','MaPiv · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Cerveza_Alhambra_-_James_Cridland.jpg','Cerveza%20Alhambra%20-%20James%20Cridland.jpg','James Cridland from London, UK · CC BY 2.0 · Wikimedia Commons'),
  ('Cerveza_Cristal.jpg','Cerveza%20Cristal.jpg','jason sager from i''m never there (home) · CC BY-SA 2.0 · Wikimedia Commons'),
  ('Chimays.jpg','Chimays.jpg','Uploaded by photographer · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Crabbelaer.jpg','Crabbelaer.jpg','Jeroen Van Hecke · CC BY 3.0 · Wikimedia Commons'),
  ('Cristal_1928.JPG','Cristal%201928.JPG','Soti · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Czaar-peter-fles-glas.jpg','Czaar-peter-fles-glas.jpg','BuroMet, copyrightholder SNAB bieren · CC BY 3.0 · Wikimedia Commons'),
  ('De-verschillende-soorten-florisbier-1396733455.jpg','De-verschillende-soorten-florisbier-1396733455.jpg','Floris Van Damme · CC BY 3.0 · Wikimedia Commons'),
  ('De_Koninck_Bolleke.jpg','De%20Koninck%20Bolleke.jpg','Mitsjol · CC BY 4.0 · Wikimedia Commons'),
  ('Dominus_double.JPG','Dominus%20double.JPG','Soti · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Dommelsch_Pilsener.jpg','Dommelsch%20Pilsener.jpg','FakirNL · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Don_de_dieu_003.jpg','Don%20de%20dieu%20003.jpg','Jmcstrav at English Wikipedia · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Dulle_Griet.JPG','Dulle%20Griet.JPG','Soti · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Edelweiss_bi%C3%A8re.JPG','Edelweiss%20bi%C3%A8re.JPG','Niko67000 · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Ename_Blond.JPG','Ename%20Blond.JPG','LeeKeoma · Public domain · Wikimedia Commons'),
  ('Englisches_Trappistenbier_Tynt_Meadow.jpg','Englisches%20Trappistenbier%20Tynt%20Meadow.jpg','Gordito1869 · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Estaminet.jpg','Estaminet.jpg','Dirk Van Esbroeck · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Ezelenbok-fles-glas.jpg','Ezelenbok-fles-glas.jpg','BuroMet, copyrightholder SNAB bieren · CC BY 3.0 · Wikimedia Commons'),
  ('Floreffe_Blond.1.jpg','Floreffe%20Blond.1.jpg','LeeKeoma · Public domain · Wikimedia Commons'),
  ('Gambrinus-Werbung_in_Karlsbad.JPG','Gambrinus-Werbung%20in%20Karlsbad.JPG','Manecke · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Geuzemegablend2011.jpg','Geuzemegablend2011.jpg','Dirk Van Esbroeck · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Goldstar_beer_from_the_tap.JPG','Goldstar%20beer%20from%20the%20tap.JPG','Koriela · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Grimbergen_blond.1.JPG','Grimbergen%20blond.1.JPG','LeeKeoma · Public domain · Wikimedia Commons'),
  ('Grisette_cerise.JPG','Grisette%20cerise.JPG','Soti · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Groen_Tuborg_bottles.jpg','Groen%20Tuborg%20bottles.jpg','Håkan Dahlström · CC BY 2.0 · Wikimedia Commons'),
  ('Grolsch_Herfstbok.jpg','Grolsch%20Herfstbok.jpg','FakirNL · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Grolsch_Kornuit.jpg','Grolsch%20Kornuit.jpg','Jasper K · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Guinness_7686a.jpg','Guinness%207686a.jpg','Harald Bischoff · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Guinness_Foreign_Extra.jpg','Guinness%20Foreign%20Extra.jpg','Mars5 · CC0 · Wikimedia Commons'),
  ('Guldenberg_beer.JPG','Guldenberg%20beer.JPG','Soti · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Gulpener_Biologsich_Ur-Pilsner.jpg','Gulpener%20Biologsich%20Ur-Pilsner.jpg','Jasper K · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Gulpener_Ch%C3%A2teau_Neubourg_Pilsner.jpg','Gulpener%20Ch%C3%A2teau%20Neubourg%20Pilsner.jpg','FakirNL · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Gulpener_Dort.jpg','Gulpener%20Dort.jpg','Jasper K · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Gulpener_Gladiator.jpg','Gulpener%20Gladiator.jpg','FakirNL · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Gulpener_HerfstBock.jpg','Gulpener%20HerfstBock.jpg','Jasper K · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Gulpener_Korenwolf.jpg','Gulpener%20Korenwolf.jpg','Jasper K · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Gulpener_Lentebock.jpg','Gulpener%20Lentebock.jpg','FakirNL · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Gulpener_Oud_Bruin.jpg','Gulpener%20Oud%20Bruin.jpg','Jasper K · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Gulpener_Pilsner.jpg','Gulpener%20Pilsner.jpg','Jasper K · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Gulpener_Ur-amber.jpg','Gulpener%20Ur-amber.jpg','FakirNL · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Gulpener_Ur-weizen.jpg','Gulpener%20Ur-weizen.jpg','FakirNL · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Gulpener_Wintervrund.jpg','Gulpener%20Wintervrund.jpg','FakirNL · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Haansewitte.jpg','Haansewitte.jpg','DirkVE · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Hanssens_Schaarbeekse_Kriek.jpg','Hanssens%20Schaarbeekse%20Kriek.jpg','Alpina~nlwiki · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Hanssens_artisanaal_oude_kriek.JPG','Hanssens%20artisanaal%20oude%20kriek.JPG','Soti · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Hapkin.JPG','Hapkin.JPG','Soti · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Headytopper.jpg','Headytopper.jpg','Alt Content · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Heineken_0.0_bier.jpg','Heineken%200.0%20bier.jpg','Grasmat · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Heineken_Oude_Bruin.JPG','Heineken%20Oude%20Bruin.JPG','Ravik at English Wikipedia · Public domain · Wikimedia Commons'),
  ('Hel_%26_Verdoemenis_Imperial_Stout_%28cropped%29.jpg','Hel%20%26%20Verdoemenis%20Imperial%20Stout%20%28cropped%29.jpg','Peijnenburg1982 · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Herkenrode_Bruin.JPG','Herkenrode%20Bruin.JPG','Queeste · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Hertog_Jan_Bockbier.JPG','Hertog%20Jan%20Bockbier.JPG','Queeste · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Hertog_Jan_Dubbel_%26_Tripel_%28old_design%29.jpg','Hertog%20Jan%20Dubbel%20%26%20Tripel%20%28old%20design%29.jpg','FakirNL · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Hertog_Jan_Grand_Prestige.JPG','Hertog%20Jan%20Grand%20Prestige.JPG','Queeste · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Hertog_Jan_Karakter.JPG','Hertog%20Jan%20Karakter.JPG','Queeste · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Hertog_Jan_Lentebock_2017.jpg','Hertog%20Jan%20Lentebock%202017.jpg','Lars van der Heide · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Hertog_Jan_Pilsener_%28new_design%29.jpg','Hertog%20Jan%20Pilsener%20%28new%20design%29.jpg','FakirNL · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Hertog_Jan_Weizener.JPG','Hertog%20Jan%20Weizener.JPG','Queeste · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Het_Anker%2C_Lucifer.jpg','Het%20Anker%2C%20Lucifer.jpg','Andreador · CC0 · Wikimedia Commons'),
  ('Hoegaarden_grand_cru.JPG','Hoegaarden%20grand%20cru.JPG','Soti · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Hop_Ruiter.JPG','Hop%20Ruiter.JPG','No machine-readable author provided. Steinsplitter assumed (based on copyright claims) · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Houblon_chouffe.jpg','Houblon%20chouffe.jpg','Dirk Van Esbroeck · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Image_bi%C3%A8re_Curtius.JPG','Image%20bi%C3%A8re%20Curtius.JPG','Arbal01 · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Jezek_11.jpg','Jezek%2011.jpg','JiriMatejicek · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Jopen_Johannieter.jpg','Jopen%20Johannieter.jpg','FakirNL · CC BY-SA 3.0 · Wikimedia Commons'),
  ('KamilGreenstone33.jpg','KamilGreenstone33.jpg','Fikstar20 · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Karjala_in_a_glass.JPG','Karjala%20in%20a%20glass.JPG','Tommi Nummelin · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Kasteel_Donker_Ingelmunster_beer_01.JPG','Kasteel%20Donker%20Ingelmunster%20beer%2001.JPG','Ccyyrree · CC0 · Wikimedia Commons'),
  ('Keizersberg.JPG','Keizersberg.JPG','Soti · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Koeketiene_glass_and_bottle.jpeg','Koeketiene%20glass%20and%20bottle.jpeg','Miguel Discart from Bruxelles, Belgique · CC BY-SA 2.0 · Wikimedia Commons'),
  ('Koff3_pullo.png','Koff3%20pullo.png','No machine-readable author provided. Qz10 assumed (based on copyright claims) · Public domain · Wikimedia Commons'),
  ('Kordaat_Pilsener.jpg','Kordaat%20Pilsener.jpg','Grasmat · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Kru%C5%A1ovice_%C4%8Cern%C3%A9_-_Mu%C5%A1ket%C3%BDr.jpg','Kru%C5%A1ovice%20%C4%8Cern%C3%A9%20-%20Mu%C5%A1ket%C3%BDr.jpg','Phyrexian · Public domain · Wikimedia Commons'),
  ('Kwak.jpg','Kwak.jpg','CC BY-SA 3.0 · Wikimedia Commons'),
  ('La_Guillotine.JPG','La%20Guillotine.JPG','Soti · CC BY-SA 3.0 · Wikimedia Commons'),
  ('La_Trappe_-_Blond.jpg','La%20Trappe%20-%20Blond.jpg','Ludovic Péron · CC BY-SA 3.0 · Wikimedia Commons'),
  ('La_Trappe_-_Dubbel.jpg','La%20Trappe%20-%20Dubbel.jpg','Ludovic Péron · CC BY-SA 3.0 · Wikimedia Commons'),
  ('La_Trappe_-_Tripel.jpg','La%20Trappe%20-%20Tripel.jpg','Ludovic Péron · CC BY-SA 3.0 · Wikimedia Commons'),
  ('La_Trappe_Isid%E2%80%99or.JPG','La%20Trappe%20Isid%E2%80%99or.JPG','LeeKeoma · CC0 · Wikimedia Commons'),
  ('La_Trappe_Quadrupel_Oak_Aged.jpg','La%20Trappe%20Quadrupel%20Oak%20Aged.jpg','Bernt Rostad · CC BY 2.0 · Wikimedia Commons'),
  ('La_Trappe_Witte_Trappist.JPG','La%20Trappe%20Witte%20Trappist.JPG','LeeKeoma · CC0 · Wikimedia Commons'),
  ('Lamme_goedzak.jpg','Lamme%20goedzak.jpg','Dirk Van Esbroeck · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Latrappepuur2.jpg','Latrappepuur2.jpg','Dirk Van Esbroeck · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Lindeboom_bierviltje.jpg','Lindeboom%20bierviltje.jpg','Lars van der Heide · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Maelstr%C3%B8m_fles_%26_glas.jpg','Maelstr%C3%B8m%20fles%20%26%20glas.jpg','BuroMet, copyrightholder SNAB bieren · CC BY 3.0 · Wikimedia Commons'),
  ('Maesbier.jpg','Maesbier.jpg','We El at Dutch Wikipedia · Public domain · Wikimedia Commons'),
  ('Molson_Export_Ale_%28290172462%29.jpg','Molson%20Export%20Ale%20%28290172462%29.jpg','KlipschFan · CC BY-SA 2.0 · Wikimedia Commons'),
  ('Mouten_Kop.jpg','Mouten%20Kop.jpg','Hopjutters · CC0 · Wikimedia Commons'),
  ('Mug_beer.JPG','Mug%20beer.JPG','Soti · CC BY-SA 4.0 · Wikimedia Commons'),
  ('N_Toeback_%28bier%29.JPG','N%20Toeback%20%28bier%29.JPG','Queeste · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Newcastle_Brown_Ale_poured_in_pint_glass.jpg','Newcastle%20Brown%20Ale%20poured%20in%20pint%20glass.jpg','Kuriosatempel · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Oesterstout.JPG','Oesterstout.JPG','Soti · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Omer_Vander_Ghinste_Bockor_Pils.jpg','Omer%20Vander%20Ghinste%20Bockor%20Pils.jpg','Miguel Discart from Bruxelles, Belgique · CC BY-SA 2.0 · Wikimedia Commons'),
  ('Orval_et_son_verre_crop.jpg','Orval%20et%20son%20verre%20crop.jpg','User:Pierrenoel derivative work: SilkTork ( talk ) · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Otter_SB_fles_%26_glas.jpg','Otter%20SB%20fles%20%26%20glas.jpg','BuroMet, copyrightholder SNAB bieren · CC BY 3.0 · Wikimedia Commons'),
  ('Oudbeitje.JPG','Oudbeitje.JPG','Soti · CC BY-SA 3.0 · Wikimedia Commons'),
  ('O%C5%BEujsko.jpg','O%C5%BEujsko.jpg','Damian Steer · Public domain · Wikimedia Commons'),
  ('Pan_to%C4%8Deni_i_boca.jpg','Pan%20to%C4%8Deni%20i%20boca.jpg','Mudroslov · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Paulaner.Salvator.JPG','Paulaner.Salvator.JPG','LeeKeoma · CC0 · Wikimedia Commons'),
  ('Pivo_Bakal%C3%A1%C5%99_1454_%28Czech_beer%29.jpg','Pivo%20Bakal%C3%A1%C5%99%201454%20%28Czech%20beer%29.jpg','Viktor Fiala (Plzeň) · CC BY 3.0 · Wikimedia Commons'),
  ('Porter_zywiec.jpg','Porter%20zywiec.jpg','Henryk Kotowski at English Wikipedia · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Prazdroj_-_Master.jpg','Prazdroj%20-%20Master.jpg','Dezidor · CC BY 2.5 · Wikimedia Commons'),
  ('RefsvindingeAle16.jpg','RefsvindingeAle16.jpg','Miguel Andrade · CC0 · Wikimedia Commons'),
  ('Rodenburg_Bronckhorster_Eigenweiss_%286814422416%29.jpg','Rodenburg%20Bronckhorster%20Eigenweiss%20%286814422416%29.jpg','walknboston · CC BY 2.0 · Wikimedia Commons'),
  ('Roock_fles_%26_glas.jpg','Roock%20fles%20%26%20glas.jpg','BuroMet, copyrightholder SNAB bieren · CC BY 3.0 · Wikimedia Commons'),
  ('SB_33cl_flesje_SG.png','SB%2033cl%20flesje%20SG.png','Scheldebrouwerij · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Saisondedottignies.jpg','Saisondedottignies.jpg','DirkVE · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Saisondepipaix.jpg','Saisondepipaix.jpg','DirkVE · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Saisonduponttweebio.jpg','Saisonduponttweebio.jpg','Dirk Van Esbroeck · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Samson_12.jpg','Samson%2012.jpg','JiriMatejicek · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Scheldepils.JPG','Scheldepils.JPG','Soti · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Schoenlappertje.jpg','Schoenlappertje.jpg','Dirk Van Esbroeck · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Silly_Saison.jpg','Silly%20Saison.jpg','Bernt Rostad from Oslo, Norway · CC BY 2.0 · Wikimedia Commons'),
  ('Sinebrychoff_Porter.jpg','Sinebrychoff%20Porter.jpg','Bernt Rostad from Oslo, Norway · CC BY 2.0 · Wikimedia Commons'),
  ('Skuumkoppe.jpg','Skuumkoppe.jpg','BonstraGeert · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Snab_Pale_Ale_fles_%26_glas.jpg','Snab%20Pale%20Ale%20fles%20%26%20glas.jpg','BuroMet, copyrightholder SNAB bieren · CC BY 3.0 · Wikimedia Commons'),
  ('Somorjai_Ferenc_Dreher_s%C3%B6r_Dreher_Antal_S%C3%B6rgy%C3%A1ri_M%C3%BAzeum_%28Budapest%29.jpg','Somorjai%20Ferenc%20Dreher%20s%C3%B6r%20Dreher%20Antal%20S%C3%B6rgy%C3%A1ri%20M%C3%BAzeum%20%28Budapest%29.jpg','Ferenc Somorjai · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Speculator_fles_%26_glas.jpg','Speculator%20fles%20%26%20glas.jpg','BuroMet, copyrightholder SNAB bieren · CC BY 3.0 · Wikimedia Commons'),
  ('Stidesbaldblond.jpg','Stidesbaldblond.jpg','Dirk Van Esbroeck · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Struis.JPG','Struis.JPG','Soti · CC BY-SA 3.0 · Wikimedia Commons'),
  ('THB_33ml.jpg','THB%2033ml.jpg','Diorit at German Wikipedia · Public domain · Wikimedia Commons'),
  ('Ter_Dolen_blond.JPG','Ter%20Dolen%20blond.JPG','Soti · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Trappist_Gregorius.jpg','Trappist%20Gregorius.jpg','DirkVE · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Tre_Fontane_et_son_calice.jpg','Tre%20Fontane%20et%20son%20calice.jpg','Damslionel · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Tuborg_beer_taps.jpg','Tuborg%20beer%20taps.jpg','abbilder · CC BY 2.0 · Wikimedia Commons'),
  ('Two_glasses_of_Heineken_Pilsener.jpg','Two%20glasses%20of%20Heineken%20Pilsener.jpg','Brodie319 · Public domain · Wikimedia Commons'),
  ('Venloosch_Alt.jpg','Venloosch%20Alt.jpg','FakirNL · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Victoria-bitter.jpg','Victoria-bitter.jpg','SteveJackson70 · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Voll-DammBotella33cl.jpg','Voll-DammBotella33cl.jpg','Voll Damm · CC BY 2.0 · Wikimedia Commons'),
  ('WestmalleTrappist.jpg','WestmalleTrappist.jpg','Saschaporsche · CC BY-SA 4.0 · Wikimedia Commons'),
  ('Wildebok.jpg','Wildebok.jpg','Dirk Van Esbroeck · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Windhoek-draught-can.jpg','Windhoek-draught-can.jpg','Bries · CC BY-SA 3.0 nl · Wikimedia Commons'),
  ('Witheer.JPG','Witheer.JPG','Soti · CC BY-SA 4.0 · Wikimedia Commons'),
  ('X-mas_beer_%28White_and_blue%29.jpeg','X-mas%20beer%20%28White%20and%20blue%29.jpeg','Royal Export · CC BY-SA 4.0 · Wikimedia Commons'),
  ('XX_Bitter.JPG','XX%20Bitter.JPG','Henxter · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Zeezuiper.jpg','Zeezuiper.jpg','Dirk Van Esbroeck · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Zlatopramen_%28Beer-_czech_republic%29.jpg','Zlatopramen%20%28Beer-%20czech%20republic%29.jpg','cs:User:Pernak · CC BY-SA 3.0 · Wikimedia Commons'),
  ('Zywiec_Beer.JPG','Zywiec%20Beer.JPG','LeeKeoma · Public domain · Wikimedia Commons')
) as v(enc_us, enc_sp, attrib)
where b.label_image_license = 'Wikimedia Commons (P18)'
  and (b.label_image_url like '%' || v.enc_us || '%' or b.label_image_url like '%' || v.enc_sp || '%');
